<#
.SYNOPSIS
    Regenerates wiki/index.md by scanning wiki folder structure.
.DESCRIPTION
    Scans wiki/entities/, wiki/concepts/, wiki/sources/, wiki/analysis/,
    wiki/requirements/, and wiki/journal/*/ to build a complete index with
    stats header, tag index, and recent activity.
.EXAMPLE
    .\generate-index.ps1
#>

$wikiRoot = (Resolve-Path (Join-Path $PSScriptRoot ".." "wiki")).Path
$indexPath = Join-Path $wikiRoot "index.md"

function Get-PageSummary($filePath) {
    $lines = Get-Content $filePath -TotalCount 20
    $inFrontmatter = $false
    $frontmatterDone = $false
    # Skip YAML frontmatter, then find first non-heading, non-empty line
    foreach ($line in $lines) {
        $trimmed = $line.Trim()
        if (-not $frontmatterDone -and $trimmed -eq "---") {
            if (-not $inFrontmatter) {
                $inFrontmatter = $true
                continue
            } else {
                $frontmatterDone = $true
                continue
            }
        }
        if ($inFrontmatter -and -not $frontmatterDone) { continue }
        # Skip headings, empty lines, author lines, and HTML comments
        if ($trimmed -and -not $trimmed.StartsWith("#") -and -not $trimmed.StartsWith("**Author") -and -not ($trimmed -match "^<!--.*-->$")) {
            return $trimmed
        }
    }
    return "(no summary)"
}

function Get-PageTags($filePath) {
    $lines = Get-Content $filePath -TotalCount 15
    $inFrontmatter = $false
    foreach ($line in $lines) {
        $trimmed = $line.Trim()
        if ($trimmed -eq "---") {
            if (-not $inFrontmatter) { $inFrontmatter = $true; continue }
            else { break }
        }
        if ($inFrontmatter -and $trimmed -match "^tags:\s*\[(.+)\]") {
            return ($Matches[1] -split ",\s*") | ForEach-Object { $_.Trim() }
        }
    }
    return @()
}

function Get-SectionEntries($folder, $linkPrefix) {
    $entries = @()
    if (Test-Path $folder) {
        Get-ChildItem $folder -Filter "*.md" | Sort-Object Name | ForEach-Object {
            $name = $_.BaseName
            $summary = Get-PageSummary $_.FullName
            $entries += "| [[$linkPrefix/$name]] | $summary |"
        }
    }
    return $entries
}

# Gather all wiki pages (excluding index.md itself)
$allPages = Get-ChildItem $wikiRoot -Recurse -Filter "*.md" | Where-Object { $_.Name -ne "index.md" -and $_.Name -ne "README.md" }
$totalPages = $allPages.Count

# Count per category
$countEntities = (Get-ChildItem (Join-Path $wikiRoot "entities") -Filter "*.md" -ErrorAction SilentlyContinue).Count
$countConcepts = (Get-ChildItem (Join-Path $wikiRoot "concepts") -Filter "*.md" -ErrorAction SilentlyContinue).Count
$countSources = (Get-ChildItem (Join-Path $wikiRoot "sources") -Filter "*.md" -ErrorAction SilentlyContinue).Count
$countAnalysis = (Get-ChildItem (Join-Path $wikiRoot "analysis") -Filter "*.md" -ErrorAction SilentlyContinue).Count

# Recent activity (5 most recently modified pages, excluding logs/journals)
$recentPages = $allPages |
    Where-Object { $_.FullName -notmatch "\\log\\" -and $_.FullName -notmatch "\\journal\\" } |
    Sort-Object LastWriteTime -Descending |
    Select-Object -First 5

# Build tag index
$tagMap = @{}
$tagFolders = @("entities", "concepts", "sources", "analysis", "requirements")
foreach ($folder in $tagFolders) {
    $folderPath = Join-Path $wikiRoot $folder
    if (Test-Path $folderPath) {
        Get-ChildItem $folderPath -Filter "*.md" | ForEach-Object {
            $pageName = "$folder/$($_.BaseName)"
            $tags = Get-PageTags $_.FullName
            foreach ($tag in $tags) {
                if ($tag) {
                    if (-not $tagMap.ContainsKey($tag)) { $tagMap[$tag] = @() }
                    $tagMap[$tag] += $pageName
                }
            }
        }
    }
}

# Build index content
$output = @()
$output += "# Wiki Index"
$output += ""
$output += "> Auto-generated by ``scripts/generate-index.ps1``. Do NOT edit manually."
$output += "> Regenerate: ``pwsh scripts/generate-index.ps1``"
$output += ""
$output += "## Stats"
$output += ""
$output += "| Metric | Count |"
$output += "| ------ | ----- |"
$output += "| Total pages | $totalPages |"
$output += "| Entities | $countEntities |"
$output += "| Concepts | $countConcepts |"
$output += "| Sources | $countSources |"
$output += "| Analysis | $countAnalysis |"
$output += "| Generated | $(Get-Date -Format 'yyyy-MM-dd HH:mm') |"
$output += ""

# Recent activity section
$output += "## Recent Activity"
$output += ""
$output += "| Page | Modified |"
$output += "| ---- | -------- |"
foreach ($page in $recentPages) {
    $relPath = $page.FullName.Replace($wikiRoot + "\", "").Replace("\", "/").Replace(".md", "")
    $modified = $page.LastWriteTime.ToString("yyyy-MM-dd HH:mm")
    $output += "| [[$relPath]] | $modified |"
}
$output += ""

# Entities
$output += "## Entities"
$output += ""
$output += "| Page | Summary |"
$output += "| ---- | ------- |"
$entitiesDir = Join-Path $wikiRoot "entities"
$output += Get-SectionEntries $entitiesDir "entities"
$output += ""

# Concepts
$output += "## Concepts"
$output += ""
$output += "| Page | Summary |"
$output += "| ---- | ------- |"
$conceptsDir = Join-Path $wikiRoot "concepts"
$output += Get-SectionEntries $conceptsDir "concepts"
$output += ""

# Sources
$output += "## Sources"
$output += ""
$output += "| Page | Summary |"
$output += "| ---- | ------- |"
$sourcesDir = Join-Path $wikiRoot "sources"
$output += Get-SectionEntries $sourcesDir "sources"
$output += ""

# Analysis
$output += "## Analysis"
$output += ""
$output += "| Page | Summary |"
$output += "| ---- | ------- |"
$analysisDir = Join-Path $wikiRoot "analysis"
$output += Get-SectionEntries $analysisDir "analysis"
$output += ""

# Requirements
$output += "## Requirements"
$output += ""
$output += "| Page | Summary |"
$output += "| ---- | ------- |"
$requirementsDir = Join-Path $wikiRoot "requirements"
$output += Get-SectionEntries $requirementsDir "requirements"
$output += ""

# Journal (per-user)
$output += "## Journal"
$output += ""
$journalRoot = Join-Path $wikiRoot "journal"
if (Test-Path $journalRoot) {
    Get-ChildItem $journalRoot -Directory | Sort-Object Name | ForEach-Object {
        $user = $_.Name
        $output += "### $user"
        $output += ""
        $output += "| Page | Summary |"
        $output += "| ---- | ------- |"
        Get-ChildItem $_.FullName -Filter "*.md" | Sort-Object Name -Descending | Select-Object -First 10 | ForEach-Object {
            $name = $_.BaseName
            $summary = Get-PageSummary $_.FullName
            $output += "| [[journal/$user/$name]] | $summary |"
        }
        $output += ""
    }
}

# Log (per-user)
$output += "## Logs"
$output += ""
$logRoot = Join-Path $wikiRoot "log"
if (Test-Path $logRoot) {
    Get-ChildItem $logRoot -Directory | Sort-Object Name | ForEach-Object {
        $user = $_.Name
        $latestLog = Get-ChildItem $_.FullName -Filter "*.md" | Sort-Object Name -Descending | Select-Object -First 1
        if ($latestLog) {
            $output += "| $user | Latest: [[log/$user/$($latestLog.BaseName)]] |"
        }
    }
}
$output += ""

# Tag Index
if ($tagMap.Count -gt 0) {
    $output += "## By Tag"
    $output += ""
    foreach ($tag in ($tagMap.Keys | Sort-Object)) {
        $pages = $tagMap[$tag] | Sort-Object
        $links = ($pages | ForEach-Object { "[[$_]]" }) -join ", "
        $output += "- **$tag**: $links"
    }
    $output += ""
}

# Write
$output | Set-Content $indexPath -Encoding UTF8
Write-Host "Index regenerated: $indexPath"
